### ISSUE TITLE
Don't run spec-up in postinstall

### ISSUE THREAD

**Issue by OR13** [csuwildcat/spec-up#5]
https://github.com/csuwildcat/spec-up/blob/master/package.json#L11

^very bad form... let the downstream devs use the tool the way they want.

**Comment by csuwildcat** [comment]
This hook simply updating the asset files for the version the dev just electively installed; the internals of the code detect the script phase and only do that portion of the work. I think there may have been a misunderstanding here, but can understand why that is - from the outside, I can understand why folks would not assume it is being smart about this internally.

**Comment by csuwildcat** [comment]
I don't think this is relevant, given the clarification, so closing atm - reopen if this doesn't make sense.

**Comment by OR13** [comment]
I prefer to use https://respec.org/docs/

and https://github.com/transmute-industries/respec-github-pages

It works with github pages without any development dependencies, and supports github deployment without using an access token / secret or a github workflow.
