### ISSUE TITLE
Move this repo to DIF

### ISSUE THREAD

**Issue by OR13** [csuwildcat/spec-up#6]
If this tool is going to be used by DIF, and we will need to maintain it.. it needs to be moved...

otherwise its a personal project dependency of DIF work items, with questionable IPR protection... and an MIT LICENSE

**Comment by csuwildcat** [comment]
Happy to do so, after we confirm that we will be allowing WGs to choose between Spec-Up and ReSpec, as they see fit.

**Comment by OR13** [comment]
having used this tool, i suggest nobody use this tool/

**Comment by csuwildcat** [comment]
> having used this tool, i suggest nobody use this tool/

Thanks Orie.
